### ISSUE TITLE
Can you support Atom-typescript?

### ISSUE THREAD

**Issue by Aedaeum** [atom/language-todo#22]
It would be really nice to have todo highlighting in my typescript probjects.

**Comment by lee-dohm** [comment]
The language-todo package injects TODO highlighting into comments in all languages (so long as they mark comments with the scope `comment`) and in plain text documents anywhere. Can you give an example of where you think it should be highligted, but isn't?

**Comment by Aedaeum** [comment]
In a typescript file, this is the object with the todo:
http://puu.sh/hImj8/0535e23f83.png

**Comment by lee-dohm** [comment]
If you look [here in the atom-typescript documentation](https://github.com/TypeStrong/atom-typescript/blob/master/CONTRIBUTING.md#dynamic-grammar), it appears that the [atom-typescript package](https://atom.io/packages/atom-typescript) goes around the standard Atom grammar system to do its own tokenization. I'm pretty certain this is what is breaking the support for injection grammars such as language-todo.

You should probably file an Issue there.

**Comment by Aedaeum** [comment]
I just want to say thanks for your quick feedback :+1:
