### ISSUE TITLE
HELP! Not sure why this isn't working for my syntax:

### ISSUE THREAD

**Issue by spencerlyon2** [atom/language-todo#28]
I am developing a new grammar for Julia files.

I have the following in my grammars/julia.cson:

```coffee
  comments:
    patterns: [
      {
        begin: "#="
        beginCaptures:
          "0":
            name: "punctuation.definition.comment.begin.julia"
        end: "=#"
        endCaptures:
          "0":
            name: "punctuation.definition.comment.end.julia"
        name: "comment.block.number-sign-equals.julia"
      }
      {
        captures:
          "1":
            name: "punctuation.definition.comment.julia"
        match: "(?<!\\$)(#)(?!\\{).*$\\n?"
        name: "comment.line.number-sign.julia"
      }
    ]
```

and I am including the `#comments` repository. (so single line comments start with `#`)

I know that this scope is being captured properly, by the following screen shot:

![screen shot 2015-06-13 at 5 16 01 pm](https://cloud.githubusercontent.com/assets/1001948/8146020/e67e0742-11ef-11e5-84b7-bdc449e46193.png)

but for some reason I can't get the `storage.type.class.todo` scope to appear.

I am pretty sure I have the language-todo package installed properly because if I just copy/paste this comment line into a python file and then check the scope at the same cursor position I get the following:

![screen shot 2015-06-13 at 5 17 28 pm](https://cloud.githubusercontent.com/assets/1001948/8146025/2bebab22-11f0-11e5-91f1-d8307eea1498.png)

Am I doing something wrong here? Thanks for entertaining!

**Comment by burodepeper** [comment]
Hey @spencerlyon2 
I don't know if you have already solved this, but I ran into the same issue. The problem lies that TODO is only recognized in patterns that have a `begin` and `end`, but not in patterns that have a `match`. I solved my issue in the following way:

```cson
comment:
  patterns: [
    {
      begin: '^\\s*(?=#)'
      end: '$'
      name: 'comment.ass'
      patterns: [
        {
          match: '^#'
          name: 'punctuation.ass'
        }
      ]
    }
  ]
```
I hope this helps.

**Comment by spencerlyon2** [comment]
@burodepeper thank you for noting. I happened to change my comment pattern to a `begin` `end` pattern and TODO started showing up, but I didn't know that was why
