### ISSUE TITLE
Doesn't detect todo in // type comments in stylus files

### ISSUE THREAD

**Issue by zenopopovici** [atom/language-todo#33]
Eg.
```
[... Code ...]

// TODO: Blahblah

[... Code ...]
```
Is this intentional?

**Comment by kevinsawicki** [comment]
What language was the code in that you aren't seeing it highlight in?

**Comment by zenopopovici** [comment]
Stylus

**Comment by zenopopovici** [comment]
It may also happen in JS.

**Comment by vchynarov** [comment]
This also does not work in Scala files.
// TODO HACK REVIEW
is not highlighted.

**Comment by nixel2007** [comment]
Doesn't work for language-1c-bsl files.
Is there something, that is needed to add in the "parrent" grammar to make things work?

**Comment by mcrawshaw** [comment]
Doesn't work in typescript (either .ts or .tsx files)

**Comment by asifm** [comment]
Doesn't' work in markdown (source.gfm) either.

**Comment by 50Wliu** [comment]
Having just fixed this in language-coffee-script, I can share some things that need to be done in order for TODO highlighting to work correctly.

The comment matches **cannot** be a simple `match` regex, eg `match: '(#).*$'`, as that won't allow language-todo to inject itself in that match.  Instead, it has to be a begin/end pattern.
https://github.com/atom/language-coffee-script/commit/ad0aa553d8f91ca1c4605da0bce5bcaf66c3e2bd

**Comment by nixel2007** [comment]
@50Wliu thanks a lot.
