### ISSUE TITLE
Keybindings

### ISSUE THREAD

**Issue by herlon214** [atom/language-todo#35]
Sorry for the newbie question but I didn't foudn the keybindings.
Maybe be a option to put into readme?

Thanks in advance.

**Comment by dsandstrom** [comment]
There's no commands in this package, so no keybindings.  Are you talking about the snippets?

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/language-todo/issues/35#issuecomment-188405115. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
