### ISSUE TITLE
The highlighting is not visible enough

### ISSUE THREAD

**Issue by marmistrz** [atom/language-todo#38]
When I add a `FIXME` in my bash script, the FIXME is barely distinguishable. The style of the highlight should be at least configurable.

**Comment by 50Wliu** [comment]
@marmistrz The highlighting is in fact totally configurable - your syntax theme controls that.  You may want to find a different syntax theme, or just apply your own styles in your `styles.less` file.

**Comment by marmistrz** [comment]
And is there any documentation available, which option pertain to the `FIXME` script?

**Comment by lee-dohm** [comment]
@marmistrz You can see [this FAQ entry](https://discuss.atom.io/t/how-do-i-determine-what-css-class-to-use-to-highlight-a-specific-syntax/23211) on [Discuss, the official Atom forum](https://discuss.atom.io).
