### ISSUE TITLE
request: View TODO list

### ISSUE THREAD

**Issue by astewart-twist** [atom/language-todo#39]
It would be great if you could show a list of all parsed TODOs and click-jump to them (like symbols tree, etc)

**Comment by ipeluffo** [comment]
Meanwhile, there are packages which implement what you are asking for, such as:
* [atom-todo-show](https://github.com/mrodalgaard/atom-todo-show)
* [todo-list](https://github.com/AnthonyCalandra/todo-list)
* [todo](https://github.com/reergymerej/todo)
* [todo-manager](https://github.com/benjaminRomano/todo-manager)

**Comment by PrakharSrivastav** [comment]
Is this feature supported yet in 2018? Or is using one of the above packages still the recommended way.

**Comment by thomasjo** [comment]
Since several community packages have implemented the desired functionality, I'm closing this issue.
