### ISSUE TITLE
Add OPTIMIZE

### ISSUE THREAD

**Issue by martinbean** [atom/language-todo#41]
Would be good if `OPTIMIZE` was highlighted (as per http://rubyquicktips.com/post/385665023/fixme-todo-and-optimize-code-comments).

**Comment by Alhadis** [comment]
Or `OPTIMISE`. :p 

Actually, I think there should be a field to allow custom tokens to be highlighted... but having written a few language packages for Atom already, I know how much of a pain-in-the-arse that'd be. :\

**Comment by inoas** [comment]
Or `OPTIMISE` (or both).

**Comment by martinbean** [comment]
Well, I’m British, but used to having to use Americanised spellings for things like `color` in CSS and whatnot. `OPTIMIZE` doesn’t bother me, either 😉

**Comment by inoas** [comment]
I am okay with having both, I am non-british/non-american btw.
*OT: However the soft-s lately bit me when I typed "supercedes" ... and was hinted with a spelling error; my "latin at school" thought.... that must be the right word. And yes, it is, in English; but not in American English.*
