### ISSUE TITLE
TODO highlighting doesnt work on Clojure files

### ISSUE THREAD

**Issue by carocad** [atom/language-todo#59]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

TODO highlighting doesnt work on Clojure

### Steps to Reproduce

1. Open a Clojure file (*.clj)
2. type `;; TODO: non sense`

**Expected behavior:** 
3. After typing ;; TODO I expected the TODO to be highlighted

**Actual behavior:** Nothing happens, it is just rendered as a normal comment

**Reproduces how often:** Only on Clojure files (so far). It works on Javascript files though.

### Versions

Atom    : 1.9.8
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
--
apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.12+
git 2.9.3

OS: Ubuntu 16.10

**Comment by 50Wliu** [comment]
This will be fixed in Atom 1.15.0.  Also, the latest stable Atom version is currently 1.13.1 - you may want to consider updating.

**Comment by carocad** [comment]
@50Wliu thanks for the quick fix :)

Regarding my Atom version, unfortunately I havent become any notification regarding atom updates. I also tried to manually check for updates but nothing happened. Is this a bug as well?

**Comment by 50Wliu** [comment]
The Linux versions currently don't auto-update or check for updates.
