### ISSUE TITLE
Add support for custom Snippets

### ISSUE THREAD

**Issue by oliverhr** [atom/language-todo#61]
Sometimes I use the TEMP tag or DEBUG, it would be nice if we can add custom snippets, and I think this can fix issues like https://github.com/atom/language-todo/issues/58 if the plugin just handle by default the most used tags like TODO and FIX so users can add its own tags/snippets.

**Comment by guywald1** [comment]
Would be very much appreciated!

**Comment by dillanjwilding** [comment]
I agree! This would be very helpful when working with teams who majority uses another IDE.

**Comment by graphicagenda** [comment]
+1

**Comment by Loschcode** [comment]
+1

**Comment by wismill** [comment]
+1
