### ISSUE TITLE
Not highlighting TODO in YAML

### ISSUE THREAD

**Issue by nwalke** [atom/language-todo#66]
### Description

I'm not seeing highlights in YAML files.

### Steps to Reproduce

1. I put this in a YAML file:
```yaml
something:
  - someitem

# TODO: Needs fixed
```
2. Note that TODO doesn't highlight

**Expected behavior:** 
I expected TODO to be highlighted in some fashion.

**Actual behavior:** 
https://i.imgur.com/XhsmH1C.png

**Reproduces how often:** 
100%

### Versions
Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
OSX

### Additional Information

I'm fairly certain that line is being detected as a comment, but not sure why the highlighting isn't firing.
https://i.imgur.com/WRPf8Mf.png

**Comment by 50Wliu** [comment]
Cannot reproduce, most likely I fixed this but it hasn't made its way to a released Atom version yet.
![yaml-todo](https://user-images.githubusercontent.com/2766036/30888672-28460ac4-a322-11e7-88cd-52a0780862a7.png)
